### PR TITLE
Bumped GHC versions, some dependency upper bounds and github action versions

### PR DESCRIPTION
**Pull request by jchia**

### CODE REVIEW

**Comment by jchia** [comment]
The change in CI compiler versions would require project settings to be updated. I think the original list of GHC versions is too old to be practical unless the project is target to some niche applications.

**Review by ysangkok — APPROVED** [review]
Thank you, looks good to me

**Comment by ysangkok** [comment]
@jchia I don't care about GHC 8.6 or 8.8, we can remove them. Is there something else that needs to be done for this to get merged?

**Comment by jchia** [comment]
> @jchia I don't care about GHC 8.6 or 8.8, we can remove them. Is there something else that needs to be done for this to get merged?

I'm not sure who's in charge of this repo, who gets to merge the commit and who gets to edit the GitHub CI part to drop GHC 8.6.5 & 8.8.3.

**Comment by ysangkok** [comment]
@NathanHowell, can you help?

**Comment by jchia** [comment]
I'm not sure what's going on with this project.

**Pull request closed without merging**
