### PR TITLE
export compressWith/decompressWith

### PR DESCRIPTION
**Pull request by domenkozar**
cc @alphaHeavy

### CODE REVIEW

**Comment by NathanHowell** [comment]
can you add an export for decompressWith too?

**Comment by domenkozar** [comment]
Done.

**Comment by NathanHowell** [comment]
great thanks, now it appears we need to migrate CI over to GitHub Actions.

**Comment by NathanHowell** [comment]
@domenkozar this has been published as https://hackage.haskell.org/package/lzma-conduit-1.2.2 thanks for the contribution.

**Comment by domenkozar** [comment]
Thank you.

**Pull request merged**
